service: sls-note-app
app: sls-note-app

frameworkVersion: "2"
useDotenv: false
variablesResolutionMode: 20210326 # for dropping ssm suffix (~true)

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1

  environment:
    MONGODB_USERNAME: ${self:custom.mongo.username}
    MONGODB_PASSWORD: ${self:custom.mongo.password}

custom:
  mongo:
    username: ${ssm:/mongodb_username}
    password: ${ssm:/mongodb_password}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
  getNotes:
    handler: handler.getNotes
    events:
      - http:
          path: /notes
          method: get
  createNote:
    handler: handler.createNote
    events:
      - http:
          path: /note
          method: post
