service: sls-note-app
app: sls-note-app

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1

  environment:
    MONGODB_USERNAME: ${self:custom.mongo.username}

custom:
  mongo:
    username: ${ssm:/mongodb_username~true}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get

plugins:
  - serverless-offline
